# Source https://github.com/daggerok/spring-boot-rest-jms-activemq/blob/master/spring-jms-docker-activemq/docker-compose.yml
version: "2.1"

services:

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [backing-services]
    volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

# HEADQUARTER Database, port: 5432
  postgres-hq:
    image: healthcheck/postgres:alpine
    ports: ["5432:5432"]
    networks: [backing-services]
    volumes: ["postgres-data-hq:/var/lib/postgresql/hq/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

# USA Factory Database, port: 5433
  postgres-us:
    image: healthcheck/postgres:alpine
    ports: ["5433:5432"]
    networks: [backing-services]
    volumes: ["postgres-data-us:/var/lib/postgresql/us/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

# CHINA Factory Database, port: 5434
  postgres-cn:
    image: healthcheck/postgres:alpine
    ports: ["5434:5432"]
    networks: [backing-services]
    volumes: ["postgres-data-cn:/var/lib/postgresql/cn/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

# MEXICO Support Center Database, port: 5435
  postgres-mx:
    image: healthcheck/postgres:alpine
    ports: ["5435:5432"]
    networks: [backing-services]
    volumes: ["postgres-data-mx:/var/lib/postgresql/mx/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

# INDIA Support Center Database, port: 5436
  postgres-in:
    image: healthcheck/postgres:alpine
    ports: ["5436:5432"]
    networks: [backing-services]
    volumes: ["postgres-data-in:/var/lib/postgresql/in/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  activemq-data: {}
  postgres-data-hq: {}
  postgres-data-us: {}
  postgres-data-cn: {}
  postgres-data-mx: {}
  postgres-data-in: {}

networks:
  backing-services:
    driver: bridge